"""The JSON Nix emits at build time, and the only build-time object here.

Everything else in the launcher is computed per launch. The spec is generated by
our own Nix from arguments Nix has already validated, so it is not untrusted
input: the failures that can actually occur are a stale spec written by an older
wrapper, which the constructors surface as a missing keyword argument, and a
spec built for the other platform, which `load_build_spec` refuses.

Declared paths stay `str` here. They are unexpanded, so `"$HOME/.claude"` is not
a path yet and `Path` would be a lie about the value; they become `Path` in
`host_state`, after expansion.
"""

from __future__ import annotations

import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal, Mapping

from launcher.constants import ERROR_PREFIX


@dataclass(frozen=True, kw_only=True)
class ProxySpec:
    binary: Path
    allowlist_file: Path
    # Testing only: maps host to "addr:port" so the proxy dials a local address
    # instead of resolving the original. Empty in every production build.
    redirects: Mapping[str, str]

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> ProxySpec:
        return cls(
            binary=Path(data["binary"]),
            allowlist_file=Path(data["allowlist_file"]),
            redirects=dict(data["redirects"]),
        )


@dataclass(frozen=True, kw_only=True)
class DependenciesLinux:
    git: Path
    bwrap: Path
    pasta: Path
    nft: Path
    ip: Path
    env: Path

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> DependenciesLinux:
        return cls(
            git=Path(data["git"]),
            bwrap=Path(data["bwrap"]),
            pasta=Path(data["pasta"]),
            nft=Path(data["nft"]),
            ip=Path(data["ip"]),
            env=Path(data["env"]),
        )


@dataclass(frozen=True, kw_only=True)
class DependenciesDarwin:
    git: Path

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> DependenciesDarwin:
        return cls(git=Path(data["git"]))


@dataclass(frozen=True, kw_only=True)
class SandboxBuildSpec:
    out_name: str
    sandbox_path: str # $PATH not Path
    allow_nix: bool
    rw_dirs: tuple[str, ...]
    rw_files: tuple[str, ...]
    ro_dirs: tuple[str, ...]
    ro_files: tuple[str, ...]
    env_keys: tuple[str, ...] # Keys only. The values are shell expressions by design, so Nix emits them as a fragment the stub sources and they never enter this process.
    allowed_local_ports: tuple[int, ...] | None # None means every host-local TCP port; the empty tuple means none.
    closure_paths_file: Path
    cacert_dir: Path
    cacert_bundle: Path
    shell: Path
    pre_entry_script: Path
    sandboxed_binary: Path
    proxy: ProxySpec | None


@dataclass(frozen=True, kw_only=True)
class SandboxBuildSpecLinux(SandboxBuildSpec):
    platform: Literal["linux"]
    hosts_file: Path
    empty_file: Path
    dependencies: DependenciesLinux


@dataclass(frozen=True, kw_only=True)
class SandboxBuildSpecDarwin(SandboxBuildSpec):
    platform: Literal["darwin"]
    dependencies: DependenciesDarwin


def _shared_fields(data: Mapping[str, Any]) -> dict[str, Any]:
    proxy = data.get("proxy")
    ports = data["allowed_local_ports"]
    return {
        "out_name": data["out_name"],
        "sandbox_path": data["sandbox_path"],
        "allow_nix": data["allow_nix"],
        "rw_dirs": tuple(data["rw_dirs"]),
        "rw_files": tuple(data["rw_files"]),
        "ro_dirs": tuple(data["ro_dirs"]),
        "ro_files": tuple(data["ro_files"]),
        "env_keys": tuple(data["env_keys"]),
        "allowed_local_ports": None if ports is None else tuple(ports),
        "closure_paths_file": Path(data["closure_paths_file"]),
        "cacert_dir": Path(data["cacert_dir"]),
        "cacert_bundle": Path(data["cacert_bundle"]),
        "shell": Path(data["shell"]),
        "pre_entry_script": Path(data["pre_entry_script"]),
        "sandboxed_binary": Path(data["sandboxed_binary"]),
        "proxy": ProxySpec.from_dict(proxy) if proxy is not None else None,
    }


def load_build_spec(path: Path) -> SandboxBuildSpecLinux | SandboxBuildSpecDarwin:
    with path.open(encoding="utf-8") as handle:
        data: Mapping[str, Any] = json.load(handle)

    platform = data["platform"]
    # The wrapper is built for one system, so this cannot happen by accident.
    # It fails loudly rather than silently rendering the wrong backend.
    if platform != sys.platform:
        raise SystemExit(
            f"{ERROR_PREFIX} {path}: built for {platform}, running on {sys.platform}"
        )

    shared = _shared_fields(data)
    if platform == "linux":
        return SandboxBuildSpecLinux(
            platform="linux",
            hosts_file=Path(data["hosts_file"]),
            empty_file=Path(data["empty_file"]),
            dependencies=DependenciesLinux.from_dict(data["dependencies"]),
            **shared,
        )
    if platform == "darwin":
        return SandboxBuildSpecDarwin(
            platform="darwin",
            dependencies=DependenciesDarwin.from_dict(data["dependencies"]),
            **shared,
        )
    raise SystemExit(f"{ERROR_PREFIX} {path}: unknown platform {platform!r}")
