#!@bash@
# The interpreter is pinned, not resolved from PATH. macOS ships bash 3.2,
# which has no mapfile at all, so `/usr/bin/env bash` turns this into a
# script that silently assembles an empty command line.
# shellcheck shell=bash
#
# What $out/bin/<outName> actually is. Identical for every wrapper and both
# platforms: the only build-time substitutions are three store paths, and it
# holds no logic beyond assembling one command line.
#
# Everything it needs, it finds by fixed name in the session directory that
# `prepare` prints. The one runtime branch is on an artifact's existence, not
# on anything decided at build time.
#
# No `set -e`. The last command is the sandbox, and its exit status is the
# status of this script; an errexit would turn a nonzero agent exit into an
# abort before the trap could run.
set -uo pipefail

# Exported rather than set per command, so the entry point that runs inside
# pasta's namespace inherits it too. `env -i` clears it before bubblewrap, so
# the sandbox never sees it.
export PYTHONPATH=@launcher@

if ! SESSION_DIR=$("@python@" -P -s -S -m launcher.prepare "@spec@"); then
  exit 1
fi

# Armed only now: before this point there is no session to clean up, and
# prepare tears down its own failures.
trap '"@python@" -P -s -S -m launcher.cleanup "$SESSION_DIR"' EXIT

# One `DECLARED_ENV+=("NAME=value")` line per declared variable, generated by
# Nix. The values are documented as runtime shell expressions, so they expand
# here and never enter Python or touch disk.
DECLARED_ENV=()
# shellcheck source=/dev/null
source "@envFragment@"

mapfile -d '' ARGV_BEFORE_ENV < "$SESSION_DIR/argv-before-env"
mapfile -d '' ARGV_AFTER_ENV < "$SESSION_DIR/argv-after-env"

# bubblewrap reads its arguments from this descriptor. Shell redirections are
# not close-on-exec, so it survives pasta, the network entry point and `env -i`,
# all of which clear the environment rather than the descriptor table. macOS
# writes no such file.
if [ -e "$SESSION_DIR/bwrap.args" ]; then
  exec 3< "$SESSION_DIR/bwrap.args"
fi

"${ARGV_BEFORE_ENV[@]}" "${DECLARED_ENV[@]}" "${ARGV_AFTER_ENV[@]}" "$@"
