"""The JSON Nix emits at build time, and the only build-time object here.

Everything else in the launcher is computed per launch. The spec is generated by
our own Nix from arguments Nix has already validated, so it is not untrusted
input: the failures that can actually occur are a stale spec written by an older
wrapper, which the constructors surface as a missing keyword argument, and a
spec built for the other platform, which `load_build_spec` refuses.

Declared paths stay `str` here. They are unexpanded, so `"$HOME/.claude"` is not
a path yet and `Path` would be a lie about the value; they become `Path` in
`host_state`, after expansion.
"""

import json
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Literal, Mapping, Self, TypedDict

from launcher.lib.constants import ERROR_PREFIX


@dataclass(frozen=True, kw_only=True)
class ProxySpec:
    binary: Path
    allowlist_file: Path
    # Testing only: maps host to "addr:port" so the proxy dials a local address
    # instead of resolving the original. Empty in every production build.
    redirects: Mapping[str, str]

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> Self:
        binary = Path(data["binary"])
        allowlist_file = Path(data["allowlist_file"])
        redirects = dict(data["redirects"])
        return cls(
            binary=binary,
            allowlist_file=allowlist_file,
            redirects=redirects,
        )


@dataclass(frozen=True, kw_only=True)
class DependenciesLinux:
    git: Path
    bwrap: Path
    pasta: Path
    nft: Path
    ip: Path
    env: Path
    # The in-namespace entry point runs before env -i, so it inherits the
    # stub's PYTHONPATH. Only the interpreter has to be named here.
    python: Path

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> Self:
        git = Path(data["git"])
        bwrap = Path(data["bwrap"])
        pasta = Path(data["pasta"])
        nft = Path(data["nft"])
        ip = Path(data["ip"])
        env = Path(data["env"])
        python = Path(data["python"])
        return cls(
            git=git, bwrap=bwrap, pasta=pasta, nft=nft, ip=ip, env=env, python=python
        )


@dataclass(frozen=True, kw_only=True)
class DependenciesDarwin:
    git: Path

    @classmethod
    def from_dict(cls, data: Mapping[str, Any]) -> Self:
        git = Path(data["git"])
        return cls(git=git)


@dataclass(frozen=True, kw_only=True)
class SandboxBuildSpec:
    out_name: str
    sandbox_path: str  # $PATH not Path
    allow_nix: bool
    rw_dirs: tuple[str, ...]
    rw_files: tuple[str, ...]
    ro_dirs: tuple[str, ...]
    ro_files: tuple[str, ...]
    env_keys: tuple[
        str, ...
    ]  # Keys only. The values are shell expressions by design, so Nix emits them as a fragment the stub sources and they never enter this process.
    allowed_local_ports: (
        tuple[int, ...] | None
    )  # None means every host-local TCP port; the empty tuple means none.
    closure_paths_file: Path
    cacert_dir: Path
    cacert_bundle: Path
    shell: Path
    pre_entry_script: Path
    sandboxed_binary: Path
    proxy: ProxySpec | None


@dataclass(frozen=True, kw_only=True)
class SandboxBuildSpecLinux(SandboxBuildSpec):
    platform: Literal["linux"]
    hosts_file: Path
    empty_file: Path
    dependencies: DependenciesLinux


@dataclass(frozen=True, kw_only=True)
class SandboxBuildSpecDarwin(SandboxBuildSpec):
    platform: Literal["darwin"]
    dependencies: DependenciesDarwin


class _CommonBuildSpec(TypedDict):
    """The fields both platforms share, typed so `**` is checked.

    Duplicates the field list on SandboxBuildSpec, which is the cost of this
    shape. mypy validates the unpacked keys against the constructor it is
    splatted into, which it cannot do for a plain dict.
    """

    out_name: str
    sandbox_path: str
    allow_nix: bool
    rw_dirs: tuple[str, ...]
    rw_files: tuple[str, ...]
    ro_dirs: tuple[str, ...]
    ro_files: tuple[str, ...]
    env_keys: tuple[str, ...]
    allowed_local_ports: tuple[int, ...] | None
    closure_paths_file: Path
    cacert_dir: Path
    cacert_bundle: Path
    shell: Path
    pre_entry_script: Path
    sandboxed_binary: Path
    proxy: ProxySpec | None


def _common_build_spec(data: Mapping[str, Any]) -> _CommonBuildSpec:
    ports = data["allowed_local_ports"]
    if ports is None:
        allowed_local_ports = None
    else:
        allowed_local_ports = tuple(ports)

    proxy_data = data.get("proxy")
    if proxy_data is None:
        proxy = None
    else:
        proxy = ProxySpec.from_dict(proxy_data)

    return _CommonBuildSpec(
        out_name=data["out_name"],
        sandbox_path=data["sandbox_path"],
        allow_nix=data["allow_nix"],
        rw_dirs=tuple(data["rw_dirs"]),
        rw_files=tuple(data["rw_files"]),
        ro_dirs=tuple(data["ro_dirs"]),
        ro_files=tuple(data["ro_files"]),
        env_keys=tuple(data["env_keys"]),
        allowed_local_ports=allowed_local_ports,
        closure_paths_file=Path(data["closure_paths_file"]),
        cacert_dir=Path(data["cacert_dir"]),
        cacert_bundle=Path(data["cacert_bundle"]),
        shell=Path(data["shell"]),
        pre_entry_script=Path(data["pre_entry_script"]),
        sandboxed_binary=Path(data["sandboxed_binary"]),
        proxy=proxy,
    )


def load_build_spec(path: Path) -> SandboxBuildSpecLinux | SandboxBuildSpecDarwin:
    with path.open(encoding="utf-8") as handle:
        data: Mapping[str, Any] = json.load(handle)

    platform = data["platform"]
    # The wrapper is built for one system, so this cannot happen by accident.
    # It fails loudly rather than silently computing for the wrong backend.
    if platform != sys.platform:
        raise SystemExit(
            f"{ERROR_PREFIX} {path}: built for {platform}, running on {sys.platform}"
        )

    common = _common_build_spec(data)
    dependencies_data = data["dependencies"]

    match platform:
        case "linux":
            return SandboxBuildSpecLinux(
                **common,
                platform="linux",
                hosts_file=Path(data["hosts_file"]),
                empty_file=Path(data["empty_file"]),
                dependencies=DependenciesLinux.from_dict(dependencies_data),
            )
        case "darwin":
            return SandboxBuildSpecDarwin(
                **common,
                platform="darwin",
                dependencies=DependenciesDarwin.from_dict(dependencies_data),
            )
        case _:
            # Reachable, unlike the match in host_state: platform comes from
            # JSON, so it is not a Literal the type checker can exhaust.
            raise SystemExit(f"{ERROR_PREFIX} {path}: unknown platform {platform!r}")
